* Umanni
Umanni is a technology company formed by HR professionals. Therefore, we understand your daily life and the challenges of managing human capital. Our technology solutions are people-focused and easy to use. Executing HR strategy in an agile manner. However, for the best access this blog was created for the dissemination of techniques and news in the area of ​​HR, so all users can interact in comments of each publication.

** Test
This test simulates a "real sprint" that I will receive as an intern at Umanni.

** Getting Started
*** You will need this
- Ruby 3.1.2
- Rails 7.0.4
- Nodejs 16.17.1
- Yarn
- Postgresql
- Redis

*** How to build the project
1. The first thing to do is intall [[https://github.com/rails/rails#getting-started][Rails]]

#+begin_src ruby
gem install rails
#+end_src

2. Clone the repository

#+begin_src bash
git clone github.com/Rinyaresu/teste-umanni.git && cd teste-umanni
#+end_src

3. Install the dependencies

#+begin_src bash
bundle install
yarn install
rails db:setup
#+end_src

*** How to test the project

#+begin_src ruby
rspec
#+end_src

You can also see the test coverage in the *coverage* folder.

#+begin_src ruby
coverage/index.html
#+end_src

*** How to run the project
#+begin_src bash
./bin/dev
#+end_src

*** Tools used
- [X] Devise
- [X] Action text
- [X] Rspec
- [X] Faker
- [X] Tailwind
- [X] Cancancan
- [ ] Action Cable

*** Seeds

The seeds create a user and amin with the following credentials to test the system:

#+begin_src bash
email: 'user@user.com'
password: password
#+end_src

#+begin_src bash
email: 'admin@admin.com'
password: password
#+end_src
